config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'

  root 'application#index'
  resources :tales, :except => [:edit]
  resources :users
  resources :sessions, :except => [:edit]
  get '/tags/:name' => 'tags#show', as: :tag
  get '/signup', to: 'users#new'
  post '/sessions/new', to: 'sessions#create'
  post '/updateline' => 'line#show'
  post '/createline' => 'line#create'
  post '/saveline' => 'line#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :user
  belongs_to :tale, inverse_of: :lines

  validate :too_many_characters
  validate :done_without_content

  def display_line
    "<div class='line' data-line-id='#{id}'><div class='entry'><h3>#{content}</h3></div>
    <div class='author'><h5><small>by</small> #{user.html_link_to_user}</h5></div></div>".html_safe
  end

  def too_many_characters
    content && content.gsub(/<br>/, "").length > 250
  end

  def done_without_content
    errors.add(:content, "cannot be empty") if done && ( no_content || too_many_characters )
  end

  def no_content
    !content || content.strip == ""
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_tales
  has_many :tales, through: :tags_tales
end

app/models/tags_tale.rb
class TagsTale < ApplicationRecord
  belongs_to :tag
  belongs_to :tale
end

app/models/tale.rb
class Tale < ApplicationRecord
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"
  has_many :lines, inverse_of: :tale, dependent: :destroy
  has_many :users, through: :lines
  has_many :tags_tales, dependent: :destroy
  has_many :tags, through: :tags_tales
  accepts_nested_attributes_for :lines
  accepts_nested_attributes_for :tags

  validates_presence_of :title
  validates :title, length: { maximum: 65}
  validates :prompt, length: { maximum: 250}

  def display_last_line
    string = String.new
    index = -1
    sorted_lines = lines.sort
    until string.length >= 250 || !sorted_lines[index] do
      string = sorted_lines[index].content + string if sorted_lines[index].done?
      index -= 1
    end
    lines_to_spaces(string)
  end

  def lines_to_spaces(string)
    string.gsub(/\<br\>/, " ").html_safe
  end

  def owner_name
    owner.username
  end

  def is_current_line_user?(user)
    lines.sort.last.user == user && !awaiting_new_line?
  end

  def awaiting_new_line?
    lines.sort.last.done?
  end

  def close
    update(open: false)
  end

  def self.open_tales
    where(open: true)
  end

  def self.closed_tales
    where(open: false)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :lines
  has_many :tales, as: :owner
  has_many :tales, -> { distinct }, through: :lines

  has_secure_password
  validates_presence_of :first_name, :last_name, :username, :email
  validates_uniqueness_of :username, :email
  validate :valid_email
  validate :minimum_six_character_password

  def valid_email
    errors.add(:email, "is not a valid email") if email !~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end

  def minimum_six_character_password
    errors.add(:password, "must be at least 6 characters") if password && password.length < 6
  end

  def tales_owned
    tales.where(owner_id: id).reverse
  end

  def tales_contributed
    tales - tales_owned
  end

  def html_link_to_user
    "<a href='/users/#{id}''>#{username}</a>".html_safe
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user

  def index
    @tales = Tale.all
    @tales2 = @tales.select { |tale| !tale.awaiting_new_line? }
    @tales = @tales.select { |tale| !@tales2.include?(tale) }
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/line_controller.rb
class LineController < ApplicationController

  before_action :set_tale
  before_action :set_line, only: [:show, :update]

  def create
    return head :forbidden if invalid_new_line?
    @line = Line.create(tale: @tale, user: @current_user)
    ActionCableBroadcaster.new(@line).create_line_broadcast
    head :ok
  end

  def show
    return head :forbidden if invalid_line?
    ActionCableBroadcaster.new(@line, params[:content]).show_line_broadcast
    head :ok
  end

  def update
    params[:content].gsub!(/\</, "&lt;")
    params[:content].gsub!(/\>/, "&gt;")
    params[:content].gsub!(/\n/, "<br>")
    return head :forbidden if invalid_line?
    return head :bad_request unless @line.update(strong_params)
    @tale.close if ready_to_close?
    ActionCableBroadcaster.new(@line).update_line_broadcast
    head :ok
  end

  private

  def strong_params
    params.permit(:content, :done)
  end

  def set_tale
    @tale = Tale.find(params[:tale])
  end

  def set_line
    @line = @tale.lines.sort.last
  end

  def invalid_new_line?
    @current_user.id != params[:id].to_i || !@tale.awaiting_new_line?
  end

  def invalid_line?
    @current_user.id != params[:id].to_i || !@tale.is_current_line_user?(@current_user)
  end

  def ready_to_close?
    params[:closed] && @current_user == @tale.owner
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to @current_user if @current_user
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "Invalid username or password"
      render 'users/signin'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to new_session_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by_name(params[:name])
    @tales = []
    if @tag
      @tales = @tag.tales
    end
  end
end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  before_action :set_tale, only: [:show, :edit]
  before_action :require_login, except: [:show, :index]
  
  def new
    @tale = Tale.new
    @line = @tale.lines.build
    @tags = Tag.new
  end

  def create
    @tale = TaleCreator.create_tale(tale_params, current_user)
    if @tale.save
      TagCreator.create_tags(tag_params, @tale)
      redirect_to @tale
    else
      @tale.errors.full_messages.each { |error| "#{error}" }
      @tags = Tag.new
      render 'new'
    end
  end

  def index
    @tales = Tale.all
    @random_tale = @tales.sample
  end

  def destroy
    @tale = current_user.tales.find(params[:id])
    @tale.destroy
    redirect_to tales_path, notice: "Your tale has been deleted."
  end

private
  def tale_params
    params.require(:tale).permit(:prompt, :title, :owner_id, lines_attributes: [:id, :content])
  end

  def tag_params
   params[:tale][:tag][:name].split(",")
  end

  def set_tale
    @tale = Tale.find(params[:id])
  end

  def require_login
    redirect_to new_session_path, notice: "You have to log in first." unless current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_new_user, only: [:new, :create]

  def create
    if @user.save
      TaleMailer.welcome_email(@user).deliver
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Tale, #{@user.first_name}! You are now logged in."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    redirect_to root_path unless @user == current_user
  end

  def show
    @user = UserDecorator.new(@user)
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_new_user
    params[:user] ? @user = User.new(user_params) : @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/application/index.html.erb
<div id="index-tales">
  <%= render partial: "tales/display_tales", locals: {tales: @tales2} %>
  <%= render partial: "tales/display_tales", locals: {tales: @tales} %>
</div>

app/views/layouts/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "flash #{key}") %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer><small>Created by Eve Essex, Alex Martin + Howard Dean Watts.</small></footer>

app/views/layouts/_navbar.html.erb
<header>
  <div id="content">
    <div id="brand">
      <%= link_to "Tale", root_path %>
    </div>
    <nav id="main-menu">
      <% if @current_user %>
        <%= link_to "Me", user_path(@current_user) %>
        <%= link_to "New", new_tale_path %>
        <%= link_to "Browse", tales_path %>
        <%= link_to "Log Out", session_path(session), method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_session_path %>
        <%= link_to "Sign Up", signup_path %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaleApp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,900,700' rel='stylesheet' type='text/css'>
    <script src="https://use.fontawesome.com/9165f73cf7.js"></script>
 
  </head>
  <%= render 'layouts/navbar' %>

  <body>
    <main>
    <%= render 'layouts/flash_messages' if !flash.empty? %>
      <div id="content">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tags/_tags_nav.html.erb
<div id="tag-nav">
  <ul>
    <% Tag.all.each do |tag| %>
      <% if tag.tales.count > 0 %>
        <li>
          <small><%= link_to "##{tag.name} (#{tag.tales.count})", tag_path(tag.name) %></small>
        </li>
      <% end %>
    <% end %>
    </ul>
  </div>

app/views/tags/show.html.erb
<div class="tags show">
  <div id="title" style="display: block;">
    <h4>
      <span class="title">Tagged with </span>
      <span class="title"><%= @tag.name %></a></span>
    </h4>
  </div>

  <div id="index-tales">
    <%= render partial: "tales/display_tales", locals: {tales: @tales} %>
  </div>

  <%= render partial: "tags/tags_nav", locals: {tales: @tales} %>
</div>

app/views/tales/_content.html.erb
<div id="tale_content">
  <% lines.each do |line| %>
    <% if line != lines.sort.last || line.tale.awaiting_new_line? %>
      <%= line.display_line %>
    <% end %>
  <% end %>
</div>

app/views/tales/_display_tales.html.erb
<% tales.each do |tale| %>
<%= link_to tale do %>
<div class="item">
    <h1><span><%= tale.title %></span></h1>
  <div class="meta">
    <div class="lines">
        <h5><%= tale.lines.count %> <%if tale.lines.count > 1 || tale.lines.count == 0 %><small>lines</small><%else%><small>Line</small><%end%></h5>
      </div>
    <div class="author"><h5><%= tale.lines.sort.last.user.username %> <small>updated <%= time_ago_in_words(tale.lines.sort.last.created_at) %> ago</small></div>
</div>
  <div class="index-text">
    <div class="index-gradient"></div>
    <span id="outerspan"> <%= tale.display_last_line %> <span id="newline" data-tale-id="<%= tale.id %>"></span></span>
  </div>
</div>
<% end %>
<% end %>

app/views/tales/_info.html.erb
<div id="title">
  <h4>
    <span class="title"><%= tale.title %></span>
    <span class="owner"> by <%= link_to tale.owner_name, tale.owner %></span>
  </h4>
</div>

<div class="title">
  <h1 class="title"><span><%= tale.title.capitalize %></span></h1>
  <% if tale.owner == @current_user %>
    <h5 id="edit-buttons">
    <i class="fa fa-trash-o"></i>
    <%= link_to " Delete Tale", tale_path(tale), method: :delete, data: {confirm: "Are you sure you want to delete this tale?"}%></h5>
  <% end %>
  <h2 class="prompt"><span><%= tale.prompt %></span></h2>
</div>

<div class="meta">
    <div class="open">
      <h5>
        <% if tale.open? %>
          <i class="fa fa-unlock-alt" aria-hidden="true"></i> <small>Open
        <% else %>
          <i class="fa fa-lock" aria-hidden="true"></i> <small>Closed
        <% end %></small>
      </h5>
    </div>
    <div class="owner">
    <h5><small>Started by</small> <%= link_to tale.owner_name, tale.owner %></h5>
    </div>
    <div class="lines">
      <h5><%= tale.lines.count %> <%if tale.lines.count > 1 || tale.lines.count == 0 %><small>lines</small><%else%><small>Line</small><%end%></h5>
    </div>
    <div class="last-updated">
      <h5><%= link_to tale.lines.sort.last.user.username, tale.lines.sort.last.user %>
      <small>updated <%= time_ago_in_words(tale.lines.sort.last.created_at) %> ago</small></h5>
    </div>
  </div>

<div class="foot">
  <div id="divider"></div>
  <h5 id="tags">
    <% tale.tags.each do |tag| %><small><%= link_to "##{tag.name}", tag_path(tag.name) %></small><% end %>
  </h5>
</div>

app/views/tales/_newline_form.html.erb
<% if tale.open? %>
<div class="new-line">
  <input type="hidden" id="curr_user_id" value="<%= session[:user_id] %>">
  <input type="hidden" id="tale_id" value="<%= tale.id %>">

  <div id="tale">
    <div class="line" id="newline" data-tale-id="<%= tale.id %>" <% if tale.is_current_line_user?(@current_user) %> contenteditable="true" <% end %> ></div>

    <div id="character-count">
    </div>
    <% if !tale.awaiting_new_line? || !@current_user || (@current_user == (tale.lines.sort.last.user)) %>
      <% participate_css = "display:none;" %>
    <% end %>
    <% if !tale.awaiting_new_line? && !tale.is_current_line_user?(@current_user)%>
      <% wait_text = "Someone is currently adding to this tale. Please stand by." %>
    <% end %>
    <% if !tale.is_current_line_user?(@current_user) %>
      <% save_css = "display:none;" %>
    <% end %>

    <% if tale.owner != @current_user || !tale.is_current_line_user?(@current_user) %>
      <% close_css = "display:none;" %>
    <% end %>

    <div class="buttons">
      <div id="participate" style="<%= participate_css %>">
        <button id="participate_btn" class="btn" >Participate in this Tale</button>
      </div>

      <div id="save" style="<%= save_css %>">
        <button id="save_btn" class="btn">Add to Tale</button>
      </div>

      <div id="close" style="<%= close_css %>">
        <button id="close_btn" class="btn">End Tale</button>
      </div>
      <span id="wait-message"><%= wait_text %></span>
    </div>
  </div>
</div>
<% end %>

app/views/tales/_tale_teaser.html.erb
<div class="tale teaser">
  <div class="title">
    <%= link_to tale do %>
      <h1 class="title"><span><%= tale.title.capitalize %></span></h1>
      <h2 class="prompt"><span><%= tale.prompt %></span></h2>
    <% end %>
  </div>

  <div class="meta">
    <div class="owner">
      <h5>Started by <%= link_to tale.owner_name, tale.owner %></h5>
    </div>
    <div class="lines">
      <h5><%= tale.lines.count %> <%if tale.lines.count > 1 || tale.lines.count == 0 %>lines<%else%>Line<%end%></h5>
    </div>
    <div class="last-updated">
      <h5><%= link_to tale.lines.sort.last.user.username, tale.lines.sort.last.user %>
      <small>updated <%= time_ago_in_words(tale.lines.sort.last.created_at) %> ago</small></h5>
    </div>
  </div>
  <div class="foot">
    <div id="divider"></div>
    <h5 id="tags"><% tale.tags.first(8).each do |tag| %><small><%= link_to "##{tag.name}", tag_path(tag.name) %></small><%end%></h5>
  </div>
</div>

app/views/tales/edit.html.erb
<h1>Edit your Tale</h1>

<%= form_for @tale do |f| %>
  <div>
    <%= f.label :prompt %>
    <%= f.text_area :prompt, :cols => 34, :rows => 5, :onkeyup => "checkMaxlength(this);", :maxlength => 250 %>
  </div>

  <div>
    <%= f.fields_for @tags do |ff| %>
     <%= ff.label :tags %>
     <%= ff.text_field :name %>
    <% end %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/tales/index.html.erb
<div id="tales" class="index">
  <div id="open-tales" class="reveal">
    <div class="menu-header">
      <h2><span class="reveal-state">+</span> Open Tales </h2>
      <span class="count"><%= Tale.open_tales.count %> entries</span>
    </div>
    <div class="items">
<% Tale.open_tales.each do |tale| %>
  <%= render 'tales/tale_teaser', tale: tale %>
<% end %>
      </div>
    </div>

 <div id="closed-tales" class="reveal">
      <div class="menu-header">
        <h2><span class="reveal-state">+</span> Closed Tales </h2>
        <span class="count"><%= Tale.closed_tales.count %> entries</span>
      </div>
      <div class="items">
<% Tale.closed_tales.each do |tale| %>
  <%= render 'tales/tale_teaser', tale: tale %>
<% end %>
      </div>
    </div>


<%= button_to "Feeling spontaneous?", @random_tale, class: "btn", method: "get" %>

  </div>
  
  <%= render partial: "tags/tags_nav", locals: {tales: @tales} %>

app/views/tales/new.html.erb
<h1>Start a new Tale</h1>

<%= form_for @tale do |f| %>

  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'newtale', :id => 'newtaletitle' %>
    <div id="character-count" class="new-tale-count"></div>
  </fieldset>

  <fieldset>
    <%= f.label :prompt %>
    <%= f.text_area :prompt, :cols => 34, :rows => 5, :class => 'newtale', :id => 'newtaleprompt' %>
    <div id="character-count" class="new-tale-count"></div>
  </fieldset>

  <fieldset>
    <%= f.fields_for :lines do |ff| %>
      <%= ff.label "The first line" %>
      <%= ff.text_area :content, :cols => 34, :rows => 5, :maxlength => 250, :class => 'newtale', :id => 'newtaleline' %>
    <% end %>
    <div id="character-count" class="new-tale-count"></div>
  </fieldset>

  <fieldset>
    <%= f.fields_for @tags do |ff| %>
     <%= ff.label :tags %>
     <%= ff.text_field :name, :class => 'newtale', :id => 'newtaletags' %>
    <% end %>
    <div id="character-count" class="new-tale-count"></div>
  </fieldset>

  <div>
    <%= f.submit "Create Tale", class: "btn btn-large" %>
  </div>

<% end %>

app/views/tales/show.html.erb
<div class="tale show">
  <%= render 'info', tale: @tale %>

  <%= render 'content', lines: @tale.lines.sort %>

  <%= render 'newline_form', tale: @tale %>
</div>

app/views/users/_errors.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(user.errors.count, "error") %> prohibited this account from being saved:</h3>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div><br>
<% end %>

app/views/users/_info.html.erb
<h1><%= @user.username %> <small>since <%= user.formatted_join_date %></small></h1>
<% if @user.my_profile(@current_user) %>
  <h5 class="edit"><%= link_to "Edit profile", edit_user_path(@user) %></h5>  
<% end %>

app/views/users/_reveal_headers.html.erb
<div class="menu-header">
  <% if owner %>
    <% if user.my_profile(current_user) %>
      <h3><span class="reveal-state"><i class="fa fa-plus" aria-hidden="true"></i></span> Tales I Own</h3>
    <% else %>
      <h3><span class="reveal-state"><i class="fa fa-plus" aria-hidden="true"></i></span><%= user.username %>'s Tales</h3>
    <% end %>
    <span class="count"><%= user.tales_owned.count %> entries</span>
  <% else %>
    <% if user.my_profile(@current_user) %>
      <h3><span class="reveal-state"><i class="fa fa-plus" aria-hidden="true"></i></span> Tales I've Contributed To</h3>
    <% else %>
      <h3><span class="reveal-state"><i class="fa fa-plus" aria-hidden="true"></i></span><%= user.username %>'s Contributions</h3>
    <% end %>
    <span class="count"><%= user.tales_contributed.count %> entries</span>
  <% end %>
</div>

app/views/users/_signup_form.html.erb
<div id="sign-in">
<%= form_for user do |f| %>
<fieldset>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</fieldset>
<fieldset>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</fieldset>
<fieldset>
  <%= f.label :username %>
  <%= f.text_field :username %>
</fieldset>
<fieldset>
  <%= f.label :email %>
  <%= f.text_field :email %>
</fieldset>
<fieldset>
  <%= f.label :password %>
  <%= f.password_field :password %>
</fieldset>
<fieldset>
  <%= f.label 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>
</fieldset>
  <%= f.submit "Sign Up", class: "btn btn-large" %>
  <div class="signup-copy">Already have an account? <%= link_to "Sign in here.", signup_path %></div>
 <% end %>
</div>

app/views/users/_tale.html.erb
<% unless owned_by_user %>
<b>Started By:</b> <%= link_to tale.owner_name, tale.owner %>
<% end %>
<b>Prompt:</b> <p> <%= tale.prompt %></p>

<b>First Line:</b> <p><%= tale.lines.first.content %></p>
<%= link_to 'View More', tale %>
<br><br>

app/views/users/_user.html.erb
<ul>
<li><b>Name:</b> <%= @user.full_name %> </li>
<li><b>Email:</b> <%= @user.email %> </li>
<li><b>Member Since:</b> <%= @user.formatted_join_date %></li>
</ul>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>

<%= render 'errors', user: @user %>

<%= form_for @user do |f| %>
<fieldset>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</fieldset>
<fieldset>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</fieldset>
<fieldset>
  <%= f.label :username %>
  <%= f.text_field :username %>
</fieldset>
<fieldset>
  <%= f.label :email %>
  <%= f.text_field :email %>
</fieldset>
<%= f.submit "Confirm Changes", class: "btn btn-large" %>
<% end %>

app/views/users/new.html.erb
<%= render 'errors', user: @user %>

<%= render 'signup_form', user: @user %>

app/views/users/show.html.erb
<div class="user show">
  <div class="profile">
    <div class="meta">
      <%= render 'info', user: @user %>
    </div>
  </div>

  <% if @user.has_contributions %>
    <div id="tales" class="index">
    <% if @user.tales_owned.count > 0 %>
      <div id="user-tales" class="reveal">
            <%= render 'users/reveal_headers', user: @user, current_user: @current_user, owner: true %>
        <div class="items">
          <% @user.tales_owned.each do |tale| %>
            <%= render 'tales/tale_teaser', tale: tale, owned_by_user: true %>
          <% end %>
        </div>
      </div>
    <% end %>

      <div id="user-contributions" class="reveal">
        <%= render 'users/reveal_headers', user: @user, current_user: @current_user, owner: false %>
        <div class="items">
        <% @user.tales_contributed.each do |tale| %>
          <%= render 'tales/tale_teaser', tale: tale, owned_by_user: false %>
        <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <h3>This user hasn't participated in any tales yet.</h3>
  <% end %>

</div>

app/views/users/signin.html.erb
<div id="sign-in">
  <%= form_for :user do |f| %>
    <fieldset>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </fieldset>
    <fieldset>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </fieldset>
    <%= f.submit "Sign In", class: "btn btn-large" %>
    <div class="signup-copy">New user? <%= link_to "Sign up here!", signup_path %></div>
    <% end %>
</div>